`numpy Basic Only`



```
Important Concepts in numpy -->
* np.array()  --> to convert it in array

*   np.shape() --> find out (row X column) Internal Strcuture
```




In [ ]:
# pip install numpy
import numpy as np

# Now how to convert a list into a array
mylist=[10,20,30]
np.array(mylist)  #Now it is act as a array

print(type(np.array(mylist)))

print(np.array(mylist))

# 2 Dimentional Array

mylist1=[[10,20,30],[40,50,60],[70,80,90],[100,110,120]]

print(np.array(mylist1))
val=np.array(mylist1[0][2])
print("The 1st row and last element is {}".format(np.array(mylist1[0][2])))

<class 'numpy.ndarray'>
[10 20 30]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
The 1st row and last element is 30


* ndarray (n-dimensional array) is the fundamental data structure in the NumPy library for Python
* `Homogeneous Data, Multi Dimentional data `

In [ ]:
# In NumPy, dtype (data type) is an object that describes the kind of data contained within a NumPy array. 1

# May be it is an int , float or anything doesnot matter for now



print(np.shape(mylist1))  #it is the way of row X column
# using space we can identify the dimention of the data




(4, 3)


Numpy Build in methods
1. arange (start,end,Increment/Decrement)

In [ ]:
np.arange(0,100,+2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Zeros((n X m )) and Ones Method in Py


*   as (row X column) Form as we want to give all zero then just need to use this

*   " " For Same same value we need to once we just give value of 1 in entier table







In [ ]:
np.zeros((2,3))

np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# getting a Random values
# using  np.random.rands(n) n--> as much we need random values

print(np.random.randn(5))


# for integer value  if we need it for that we need
# np.random.randint(start,end)
# -->start<end
# -- it will give a random value from this range

print(np.random.randint(-10,100))



[ 1.19544384 -0.59690273  0.80968763 -0.74052173 -0.531744  ]
-8
