In [ ]:
# Panda
# pip install pandas
import pandas as pd


1. df.head()       # First 5 rows
2. df.tail()       # Last 5 rows
3. df.info()       # Summary
4. df.describe()   # Stats
5. df.shape        # Rows, Columns
6. df.columns      # Column names

Series
 --> in Series 'S' is always Capital Letter


```
 pd.Series(data, index)
  --> Data or index should Enter in the form of List
  --> Series.value --> data
  --> Series.index  -->index value

s = pd.Series([100, 200, 300], index=['x', 'y', 'z'])
print(s)

```



In [3]:
# access Series using List and about Default Indexing
my_list=[100,200,300]
Series1=pd.Series(my_list)
print (Series1)


# pd.Series(data=my_list,index=['x','y','z']) or
Series2= pd.Series(data=[111,222,333],index=['x','y','z'])

# Series Functionalities are :
print(Series2.index)    #for Index data Fetch

print(Series2.values)


print(Series2['y'])  #using index  value
print(Series2[2]) #using default sequnce value



0    100
1    200
2    300
dtype: int64
Index(['x', 'y', 'z'], dtype='object')
[111 222 333]
222
333


C:\Users\Debajit Samanta\AppData\Local\Temp\ipykernel_1232\2102297584.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(Series2[2]) #using default sequnce value


In [4]:
# Using numpy array also you can add the data
import numpy as np

arr=np.array([10,15,20])
# Series3=pd.Series(arr)

index=['a','b','c']
Series3=pd.Series(data=arr,index=index)
print(Series3[0])

10


C:\Users\Debajit Samanta\AppData\Local\Temp\ipykernel_1232\4152523018.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(Series3[0])


Uisng Dict{}

In [5]:
my_dict={'a':100,'b':200}
Series4=pd.Series(my_dict)
print(Series4)

a    100
b    200
dtype: int64


Data Frame
* 📊 Pandas DataFrame – Short Notes
A DataFrame is a two-dimensional labeled data structure (like a table).

It consists of rows and columns.

Each column in a DataFrame is a Series.

`Syntax: pd.DataFrame(data)`

Can hold different data types in different columns.



In [ ]:
df=pd.DataFrame([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
print(df)
print(df.shape,df.index,"\n", df.values)

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90
(3, 3) RangeIndex(start=0, stop=3, step=1) 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


we can add index (refer as ROW) and column values 


In [11]:
df2=pd.DataFrame([[10,20,30],
                 [40,50,60],
                 [70,80,90]],
                 index=['a','b','c'],
                 columns=[1,2,3]
                 
                 )
print(df2)

    1   2   3
a  10  20  30
b  40  50  60
c  70  80  90


1 2 3 4
