In [14]:
import pandas as pd
import numpy as np

In [16]:
value=[[1,2,3,4],[10,20,30,40],[100,200,300,400]]
index=['Zerobase','twozero base','three zero base']

Series1=pd.Series(data=value,index=index)
print(Series1.info)

<bound method Series.info of Zerobase                   [1, 2, 3, 4]
twozero base           [10, 20, 30, 40]
three zero base    [100, 200, 300, 400]
dtype: object>


In [28]:
# using dict
dict={'name':{'DEBAJIT SAMANTA','abc'},'Place':{'Nandigram','Kolkata'}}
# print(dict)

Series2=pd.Series(dict)
print(Series2.values)
print(Series2.index)

print(Series2.shape)
print(Series2.describe)

[{'DEBAJIT SAMANTA', 'abc'} {'Kolkata', 'Nandigram'}]
Index(['name', 'Place'], dtype='object')
(2,)
<bound method NDFrame.describe of name     {DEBAJIT SAMANTA, abc}
Place      {Kolkata, Nandigram}
dtype: object>


In [13]:
print(Series1.index)
print(Series1.values)

print(Series1['Zerobase'][1])
print(Series1[0][1])

Index(['Zerobase', 'twozero base', 'three zero base'], dtype='object')
[list([1, 2, 3, 4]) list([10, 20, 30, 40]) list([100, 200, 300, 400])]
2
2


/tmp/ipykernel_29449/1789973228.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(Series1[0][1])


Data Frame 

In [40]:
# df=pd.DataFrame([[1,2,3,4],
#                 [10,20,30,40],
#                 [100,200,300,400]])
df=pd.DataFrame([[1,2,3,4],
                [10,20,30,40],
                [100,200,300,400]],
                index=['1s value','2s Value','3s value'],
                columns=['col1','col2','col3','col4'])

print(df)

print(df.index)
print(df.values)

print(df.shape)

          col1  col2  col3  col4
1s value     1     2     3     4
2s Value    10    20    30    40
3s value   100   200   300   400
Index(['1s value', '2s Value', '3s value'], dtype='object')
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]
(3, 4)
