In [2]:
import pandas as pd
import numpy as np

In [3]:
value=[[1,2,3,4],[10,20,30,40],[100,200,300,400]]
index=['Zerobase','twozero base','three zero base']

Series1=pd.Series(data=value,index=index)
print(Series1.info)

<bound method Series.info of Zerobase                   [1, 2, 3, 4]
twozero base           [10, 20, 30, 40]
three zero base    [100, 200, 300, 400]
dtype: object>


In [4]:
# using dict
dict={'name':{'DEBAJIT SAMANTA','abc'},'Place':{'Nandigram','Kolkata'}}
# print(dict)

Series2=pd.Series(dict)
print(Series2.values)
print(Series2.index)

print(Series2.shape)
print(Series2.describe)

[{'abc', 'DEBAJIT SAMANTA'} {'Kolkata', 'Nandigram'}]
Index(['name', 'Place'], dtype='object')
(2,)
<bound method NDFrame.describe of name     {abc, DEBAJIT SAMANTA}
Place      {Kolkata, Nandigram}
dtype: object>


In [5]:
print(Series1.index)
print(Series1.values)

print(Series1['Zerobase'][1])
print(Series1[0][1])

Index(['Zerobase', 'twozero base', 'three zero base'], dtype='object')
[list([1, 2, 3, 4]) list([10, 20, 30, 40]) list([100, 200, 300, 400])]
2
2


/tmp/ipykernel_1174/1789973228.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(Series1[0][1])


Data Frame 

In [6]:
# df=pd.DataFrame([[1,2,3,4],
#                 [10,20,30,40],
#                 [100,200,300,400]])
df=pd.DataFrame([[1,2,3,4],
                [10,20,30,40],
                [100,200,300,400]],
                index=['1s value','2s Value','3s value'],
                columns=['col1','col2','col3','col4'])

print(df)

print(df.index)
print(df.values)

print(df.shape)

          col1  col2  col3  col4
1s value     1     2     3     4
2s Value    10    20    30    40
3s value   100   200   300   400
Index(['1s value', '2s Value', '3s value'], dtype='object')
[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]
(3, 4)


project task 

In [7]:
weather_df=pd.read_csv("weather_2012.csv")

In [8]:
# print(weather_df.shape)
# print(weather_df.columns)
# print(weather_df.info)
# print(weather_df.index)
# print(weather_df.tail(10))

print(weather_df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Date/Time           8784 non-null   object 
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64  
 4   Wind Spd (km/h)     8784 non-null   int64  
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object 
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB
None


In [9]:
print(weather_df['Wind Spd (km/h)'].head(10))

0     4
1     4
2     7
3     6
4     7
5     9
6     7
7     7
8     9
9    15
Name: Wind Spd (km/h), dtype: int64


In [10]:
print(type(weather_df['Weather']))

<class 'pandas.core.series.Series'>


In [11]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Date/Time           8784 non-null   object 
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64  
 4   Wind Spd (km/h)     8784 non-null   int64  
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object 
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB


In [15]:
weather_df['Date/Time']=pd.to_datetime(weather_df['Date/Time'],errors='coerce')

In [17]:
weather_df.info()
print(type(weather_df['Date/Time']))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB
<class 'pandas.core.series.Series'>


In [18]:
# print unique values 

print(weather_df['Weather'].unique())

['Fog' 'Freezing Drizzle,Fog' 'Mostly Cloudy' 'Cloudy' 'Rain'
 'Rain Showers' 'Mainly Clear' 'Snow Showers' 'Snow' 'Clear'
 'Freezing Rain,Fog' 'Freezing Rain' 'Freezing Drizzle' 'Rain,Snow'
 'Moderate Snow' 'Freezing Drizzle,Snow' 'Freezing Rain,Snow Grains'
 'Snow,Blowing Snow' 'Freezing Fog' 'Haze' 'Rain,Fog' 'Drizzle,Fog'
 'Drizzle' 'Freezing Drizzle,Haze' 'Freezing Rain,Haze' 'Snow,Haze'
 'Snow,Fog' 'Snow,Ice Pellets' 'Rain,Haze' 'Thunderstorms,Rain'
 'Thunderstorms,Rain Showers' 'Thunderstorms,Heavy Rain Showers'
 'Thunderstorms,Rain Showers,Fog' 'Thunderstorms' 'Thunderstorms,Rain,Fog'
 'Thunderstorms,Moderate Rain Showers,Fog' 'Rain Showers,Fog'
 'Rain Showers,Snow Showers' 'Snow Pellets' 'Rain,Snow,Fog'
 'Moderate Rain,Fog' 'Freezing Rain,Ice Pellets,Fog'
 'Drizzle,Ice Pellets,Fog' 'Drizzle,Snow' 'Rain,Ice Pellets'
 'Drizzle,Snow,Fog' 'Rain,Snow Grains' 'Rain,Snow,Ice Pellets'
 'Snow Showers,Fog' 'Moderate Snow,Blowing Snow']


In [21]:
weather_df['Wind Spd (km/h)'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [37]:
# weather_df['Wind Spd (km/h)'].nunique()
# print(len(weather_df['Wind Spd (km/h)'].unique()))
print(weather_df)

               Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24            

In [ ]:
# print(weather_df['Weather'].head())
# print(weather_df['Weather'].value_counts())
# weather_df['Weather'].value_counts() → 
# This counts how many times each unique weather condition appears
#  and returns a sorted list.

# [2] → This selects the third most frequent weather condition.
print(weather_df['Weather'].value_counts())
print(weather_df['Weather'].value_counts()[0])
# measn from value_counts() 1st sorted 

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [41]:
print(weather_df['Weather'].value_counts().get('Clear','Not available'))
print(weather_df['Weather'].value_counts().get('clear','Not available'))
# 2nd one cause c is small 


print(weather_df['Wind Spd (km/h)'].value_counts().get(4,"No 4KM/hr Spped is their "))

1326
Not available
474
